import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="ALLUCO | Aluminium in motion", page_icon="A", layout="wide", initial_sidebar_state="collapsed")

st.markdown(r"""
<style>
html, body, [data-testid="stAppViewContainer"], .stApp { margin:0!important; padding:0!important; background:#f3f1ec!important; overflow:hidden!important; }
[data-testid="stHeader"],[data-testid="stToolbar"],[data-testid="stDecoration"],[data-testid="stStatusWidget"],footer,#MainMenu {display:none!important}
[data-testid="stMain"], [data-testid="stMainBlockContainer"], .block-container {padding:0!important;margin:0!important;max-width:100%!important;width:100%!important}
[data-testid="stVerticalBlock"]{gap:0!important}
iframe{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;min-height:100vh!important;border:0!important;display:block!important}
</style>
""", unsafe_allow_html=True)

SITE_HTML = r"""<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#f3f1ec">
<meta name="description" content="ALLUCO - aluminium, import export, logistique et systemes architecturaux.">
<title>ALLUCO | Aluminium in motion</title>
<script src="https://cdn.jsdelivr.net/npm/three@0.152.2/build/three.min.js"></script>
<style>
:root{
  --paper:#f3f1ec;--paper2:#fbfaf7;--ink:#111417;--muted:#66707a;--line:rgba(17,20,23,.13);
  --blue:#176cba;--blue2:#69a8d9;--sage:#8ab9ad;--shadow:0 28px 80px rgba(27,35,42,.10)
}
*{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--paper)}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow-x:hidden}a{color:inherit;text-decoration:none}button{font:inherit}
#webgl{position:fixed;inset:0;width:100%;height:100%;z-index:0;display:block}.veil{position:fixed;inset:0;z-index:1;pointer-events:none;background:linear-gradient(90deg,rgba(243,241,236,.94) 0%,rgba(243,241,236,.58) 34%,rgba(243,241,236,.05) 66%,rgba(243,241,236,.18) 100%)}
.topbar{position:fixed;inset:0 0 auto 0;height:74px;z-index:90;padding:0 clamp(22px,4vw,68px);display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);background:rgba(251,250,247,.72);backdrop-filter:blur(18px)}
.brand{display:flex;align-items:center;gap:12px;font-size:.86rem;font-weight:900;letter-spacing:.16em}.brand-emblem{width:34px;height:34px;position:relative;border:1px solid rgba(17,20,23,.18);background:linear-gradient(145deg,#fff,#aab3bb);overflow:hidden}.brand-emblem:before{content:"";position:absolute;inset:7px 8px 8px;border-left:3px solid #25303a;border-bottom:3px solid #25303a;transform:skew(-14deg)}.brand-emblem:after{content:"";position:absolute;width:3px;height:21px;background:var(--blue);left:16px;top:6px;transform:skew(-14deg)}
.nav{display:flex;gap:26px;align-items:center;text-transform:uppercase;letter-spacing:.13em;font-size:.66rem;font-weight:780;color:#5c6670}.nav a:hover{color:var(--ink)}.nav .cta{padding:10px 14px;border:1px solid var(--line);background:rgba(255,255,255,.55)}
.menu{display:none;border:0;background:transparent}.menu span{display:block;width:22px;height:1px;margin:5px;background:#111}
main{position:relative;z-index:4}.panel{position:relative;min-height:100svh;padding:118px clamp(24px,6.5vw,104px) 84px;display:flex;align-items:center}.hero{min-height:112svh}.copy{width:min(680px,58vw)}.eyebrow,.chapter,.section-kicker{margin:0 0 18px;color:var(--blue);font-size:.64rem;letter-spacing:.2em;text-transform:uppercase;font-weight:900}.hero h1{margin:0;max-width:800px;font-size:clamp(4.3rem,8.1vw,9.2rem);line-height:.84;letter-spacing:-.068em;font-weight:840}.hero h1 span{display:block;color:#6a747d;font-weight:560}.lead{max-width:570px;margin:28px 0 0;color:var(--muted);font-size:clamp(1rem,1.4vw,1.24rem);line-height:1.72}.actions{display:flex;gap:11px;flex-wrap:wrap;margin-top:32px}.btn{display:inline-flex;align-items:center;justify-content:center;padding:13px 18px;border:1px solid var(--line);text-transform:uppercase;letter-spacing:.11em;font-size:.68rem;font-weight:850;background:rgba(255,255,255,.62)}.btn.primary{background:#11161b;color:#fff;border-color:#11161b}
.hero-meta{position:absolute;right:clamp(24px,5vw,82px);bottom:46px;display:flex;gap:32px;padding-top:14px;border-top:1px solid var(--line)}.hero-meta div{display:flex;flex-direction:column;gap:4px}.hero-meta span{font-size:.54rem;color:#7c8790;letter-spacing:.13em}.hero-meta b{font-size:.7rem;letter-spacing:.07em}
.story-card{width:min(520px,42vw);padding:30px 34px;border-left:2px solid var(--blue);background:linear-gradient(90deg,rgba(255,255,255,.93),rgba(255,255,255,.68));backdrop-filter:blur(16px);box-shadow:var(--shadow);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.align-right{justify-content:flex-end}.story-card h2{margin:0 0 17px;font-size:clamp(2.35rem,4.1vw,4.7rem);line-height:.96;letter-spacing:-.052em}.story-card p:not(.chapter){margin:0;color:var(--muted);line-height:1.72}.story-specs{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:24px;padding-top:17px;border-top:1px solid var(--line)}.story-specs span{display:block;font-size:.55rem;color:#87919a;letter-spacing:.11em}.story-specs b{display:block;margin-top:4px;font-size:.73rem}
.stage{position:fixed;z-index:50;right:20px;top:50%;transform:translateY(-50%);display:flex;flex-direction:column;gap:11px}.stage button{width:8px;height:8px;border-radius:50%;border:1px solid rgba(17,20,23,.4);background:rgba(255,255,255,.55);padding:0;cursor:pointer;transition:.25s}.stage button.is-active{background:var(--blue);border-color:var(--blue);box-shadow:0 0 0 5px rgba(23,108,186,.12)}
.scene-labels{position:fixed;z-index:6;inset:0;pointer-events:none}.scene-label{position:absolute;padding:8px 10px;border:1px solid rgba(17,20,23,.10);background:rgba(255,255,255,.78);backdrop-filter:blur(12px);font-size:.58rem;letter-spacing:.11em;text-transform:uppercase;color:#5c6670;opacity:0;transition:opacity .3s ease}.scene-label.on{opacity:1}.l-air{right:10%;top:19%}.l-road{right:18%;top:39%}.l-port{right:12%;top:52%}.l-wh{right:18%;top:26%}.l-alu{right:11%;top:36%}
.loader{position:fixed;inset:0;z-index:130;background:#f3f1ec;display:grid;place-items:center;transition:opacity .5s,visibility .5s}.loader.off{opacity:0;visibility:hidden}.loader-box{width:min(480px,calc(100% - 46px))}.loader-brand{font-size:1.3rem;font-weight:950;letter-spacing:.2em}.loader-sub{margin-top:15px;color:#74808a;font-size:.61rem;letter-spacing:.14em}.loader-track{height:1px;background:#d2d7da;margin-top:20px}.loader-track span{display:block;width:0;height:100%;background:var(--blue);transition:width .25s}
.content-section{position:relative;z-index:10;padding:112px clamp(24px,6vw,96px);background:#fff;border-top:1px solid var(--line)}.surface-alt{background:#f0f2f2}.content-wrap{width:min(1280px,100%);margin:auto}.section-heading{display:grid;grid-template-columns:1.15fr .85fr;gap:58px;align-items:end;margin-bottom:48px}.section-heading h2,.contact-hero h2{margin:0;font-size:clamp(2.8rem,5vw,5.8rem);line-height:.95;letter-spacing:-.055em}.section-heading p,.contact-hero p{margin:0;color:var(--muted);line-height:1.75}.stats{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line)}.stats article{min-height:138px;padding:28px;background:#fff;border-right:1px solid var(--line);border-bottom:1px solid var(--line);display:flex;flex-direction:column;justify-content:space-between}.stats strong{font-size:clamp(2rem,3vw,3.5rem);letter-spacing:-.05em;font-weight:680}.stats span{color:var(--muted);font-size:.75rem}.catalog{display:grid;grid-template-columns:repeat(2,1fr);border-left:1px solid var(--line);border-top:1px solid var(--line)}.catalog article{padding:30px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);background:#fff}.catalog h3{margin:0 0 14px;font-size:1.35rem}.catalog p,.catalog li{color:var(--muted);line-height:1.65}.catalog ul{padding-left:18px;margin:15px 0 0}.contact-section{background:#111820;color:#f4f7f8}.contact-section .section-kicker{color:#71b4ec}.contact-section p{color:#a7b2bc}.contact-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:rgba(255,255,255,.12);margin-top:36px}.contact-grid>*{padding:23px;background:#111820;display:flex;flex-direction:column;gap:7px}.contact-grid span{font-size:.58rem;letter-spacing:.12em;color:#81909c;text-transform:uppercase}.contact-grid strong{font-size:.88rem}.footer{display:flex;justify-content:space-between;gap:20px;margin-top:54px;padding-top:22px;border-top:1px solid rgba(255,255,255,.12);font-size:.72rem;color:#99a7b2}.footer b{color:#fff;letter-spacing:.16em}
@media(max-width:900px){.nav{position:fixed;top:74px;left:0;right:0;background:#fbfaf7;padding:24px;display:none;flex-direction:column;align-items:flex-start;border-bottom:1px solid var(--line)}.nav.open{display:flex}.menu{display:block}.panel{padding:106px 22px 92px}.copy{width:100%}.hero h1{font-size:clamp(3.5rem,17vw,6.5rem)}.story-card{width:min(100%,590px)}.align-right{justify-content:flex-start}.hero-meta{display:none}.section-heading{grid-template-columns:1fr;gap:22px}.stats{grid-template-columns:1fr 1fr}.catalog{grid-template-columns:1fr}.contact-grid{grid-template-columns:1fr 1fr}.scene-labels{display:none}}
@media(max-width:560px){.stats,.contact-grid{grid-template-columns:1fr}.stage{display:none}}
</style>
</head>
<body>
<div class="loader" id="loader"><div class="loader-box"><div class="loader-brand">ALLUCO</div><div class="loader-sub" id="loaderText">BUILDING THE SUPPLY CHAIN...</div><div class="loader-track"><span id="loaderBar"></span></div></div></div>
<header class="topbar"><a class="brand" href="#home"><span class="brand-emblem"></span><span>ALLUCO</span></a><nav class="nav" id="nav"><a href="#journey">Logistics</a><a href="#warehouse">Stock</a><a href="#products">Aluminium</a><a href="#company">Company</a><a class="cta" href="#contact">Contact</a></nav><button class="menu" id="menu"><span></span><span></span></button></header>
<canvas id="webgl"></canvas><div class="veil"></div>
<div class="stage" id="stage"><button data-go="home"></button><button data-go="journey"></button><button data-go="road"></button><button data-go="port"></button><button data-go="warehouse"></button><button data-go="aluminium"></button></div>
<div class="scene-labels"><div class="scene-label l-air" data-label="1">International sourcing</div><div class="scene-label l-road" data-label="2">ALLUCO road fleet</div><div class="scene-label l-port" data-label="3">Port & containers</div><div class="scene-label l-wh" data-label="4">ALLUCO warehouse</div><div class="scene-label l-alu" data-label="5">Aluminium systems</div></div>
<main>
<section class="panel hero" id="home" data-scene="0"><div class="copy"><p class="eyebrow">ALUMINIUM &bull; IMPORT &bull; EXPORT &bull; TUNISIA</p><h1>ALLUCO.<span>ONE CONNECTED FLOW.</span></h1><p class="lead">A continuous 3D logistics world linking international sourcing, ALLUCO trucks, maritime transport, port handling, stock and aluminium systems.</p><div class="actions"><a class="btn primary" href="#journey">Explore the flow</a><a class="btn" href="#company">Discover ALLUCO</a></div></div><div class="hero-meta"><div><span>01</span><b>GLOBAL SUPPLY</b></div><div><span>02</span><b>LOGISTICS</b></div><div><span>03</span><b>ALUMINIUM</b></div></div></section>
<section class="panel" id="journey" data-scene="1"><article class="story-card"><p class="chapter">01 &mdash; INTERNATIONAL SOURCING</p><h2>Global supply.<br>One destination.</h2><p>The camera opens above a connected industrial landscape. Aircraft, roads and freight routes converge toward the ALLUCO logistics network.</p><div class="story-specs"><div><span>FLOW</span><b>International</b></div><div><span>MODE</span><b>Air / Road</b></div><div><span>HUB</span><b>Tunisia</b></div></div></article></section>
<section class="panel align-right" id="road" data-scene="2"><article class="story-card"><p class="chapter">02 &mdash; ALLUCO ROAD FLEET</p><h2>The brand<br>on the move.</h2><p>ALLUCO-branded trucks travel through the same 3D world, linking terminal, warehouse and distribution points with a single continuous route.</p><div class="story-specs"><div><span>FLEET</span><b>ALLUCO</b></div><div><span>LOAD</span><b>Aluminium</b></div><div><span>FLOW</span><b>Continuous</b></div></div></article></section>
<section class="panel" id="port" data-scene="3"><article class="story-card"><p class="chapter">03 &mdash; MARITIME LOGISTICS</p><h2>Port. Cargo.<br>Containers.</h2><p>A container vessel, gantry cranes and stacked cargo form the maritime layer of the supply chain. The road network continues directly into the port.</p><div class="story-specs"><div><span>MODE</span><b>Sea freight</b></div><div><span>HANDLING</span><b>Gantry</b></div><div><span>UNIT</span><b>Container</b></div></div></article></section>
<section class="panel align-right" id="warehouse" data-scene="4"><article class="story-card"><p class="chapter">04 &mdash; ALLUCO WAREHOUSE</p><h2>Receive.<br>Store. Prepare.</h2><p>The ALLUCO depot appears as an open industrial building with racks, stock zones and a forklift moving aluminium loads inside the same logistics environment.</p><div class="story-specs"><div><span>STOCK</span><b>Profiles</b></div><div><span>HANDLING</span><b>Forklift</b></div><div><span>STATUS</span><b>Ready</b></div></div></article></section>
<section class="panel" id="aluminium" data-scene="5"><article class="story-card"><p class="chapter">05 &mdash; ALUMINIUM SYSTEMS</p><h2>From logistics<br>to architecture.</h2><p>The journey ends on aluminium profiles and systems: the physical product delivered by the entire chain.</p><div class="story-specs"><div><span>PRODUCT</span><b>Profiles</b></div><div><span>FINISH</span><b>Premium</b></div><div><span>MARKET</span><b>Architecture</b></div></div></article></section>
<section class="content-section" id="company"><div class="content-wrap"><p class="section-kicker">ALLUCO</p><div class="section-heading"><h2>Aluminium systems with an industrial backbone.</h2><p>ALLUCO develops architectural aluminium systems and supports projects through product development, surface finishing, stock, logistics and an international commercial network.</p></div><div class="stats"><article><strong>2008</strong><span>Foundation</span></article><article><strong>11,750 m&sup2;</strong><span>Industrial site announced</span></article><article><strong>350 t/month</strong><span>Production capacity announced</span></article><article><strong>600+</strong><span>Profiles / dies developed</span></article><article><strong>450+</strong><span>Colours and finishes</span></article><article><strong>10 years</strong><span>Surface-treatment warranty announced</span></article></div></div></section>
<section class="content-section surface-alt" id="products"><div class="content-wrap"><p class="section-kicker">PRODUCT SYSTEMS</p><div class="section-heading"><h2>Architectural aluminium, organised by application.</h2><p>Public ALLUCO product families include door and window systems, indoor solutions, outdoor solutions and guardrail / fencing systems.</p></div><div class="catalog"><article><h3>Door & Window Systems</h3><ul><li>ALTO 15400</li><li>KLIMA 7400</li><li>OIKOS 4700</li><li>Prima 6300</li><li>SUPRA 6000</li><li>Square 40 / Square 67</li></ul></article><article><h3>Indoor</h3><ul><li>Dressing Alluco</li><li>Parolit shower partition</li><li>Folding & sliding doors</li><li>Glass interior doors</li><li>Pivot doors</li><li>VEROLIT interior glazing</li></ul></article><article><h3>Outdoor</h3><ul><li>Roller shutter slats</li><li>Pergola Azore</li></ul></article><article><h3>Guardrails & Fencing</h3><ul><li>BlendLine guardrail</li><li>Gates & fencing</li></ul></article></div></div></section>
<section class="content-section contact-section" id="contact"><div class="content-wrap"><p class="section-kicker">CONTACT</p><div class="contact-hero"><h2>Build the next aluminium project.</h2><p>Public ALLUCO contact details.</p></div><div class="contact-grid"><a href="mailto:info@alluco.com"><span>Email</span><strong>info@alluco.com</strong></a><a href="tel:+21670284142"><span>Soukra</span><strong>+216 70 284 142</strong></a><a href="tel:+21670284140"><span>Moknine</span><strong>+216 70 284 140</strong></a><div><span>Soukra</span><strong>64 BIS Av. Fattouma Bourguiba, Tunis</strong></div></div><div class="footer"><b>ALLUCO</b><span>Aluminium &bull; Systems &bull; Logistics &bull; International</span></div></div></section>
</main>
<script>
(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const loader=$('#loader'),loaderBar=$('#loaderBar'),loaderText=$('#loaderText'),canvas=$('#webgl'),sections=$$('[data-scene]'),stageBtns=$$('#stage button'),labels=$$('.scene-label');
const mobile=matchMedia('(max-width:900px)').matches,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
$('#menu').addEventListener('click',()=>$('#nav').classList.toggle('open')); $$('#nav a').forEach(a=>a.addEventListener('click',()=>$('#nav').classList.remove('open'))); stageBtns.forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.go).scrollIntoView({behavior:'smooth'})));
function prog(n,t){loaderBar.style.width=n+'%';if(t)loaderText.textContent=t} prog(15,'INITIALISING ALLUCO WORLD...');
function webglOK(){try{const c=document.createElement('canvas');return !!(window.WebGLRenderingContext&&(c.getContext('webgl2')||c.getContext('webgl')))}catch(e){return false}}
if(!window.THREE||!webglOK()){prog(100,'3D UNAVAILABLE');setTimeout(()=>loader.classList.add('off'),350);return}
const THREE=window.THREE; const scene=new THREE.Scene();scene.background=new THREE.Color(0xf3f1ec);scene.fog=new THREE.FogExp2(0xf3f1ec,mobile?.009:.0065);
const camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.1,700);const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.15:1.55));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const world=new THREE.Group();scene.add(world); const C={paper:0xf3f1ec,white:0xfaf9f6,road:0xd5d5d0,roadEdge:0xbec2c2,graphite:0x27313a,deep:0x141b20,steel:0x7e8991,alu:0xb9c1c7,alu2:0xe4e7e8,blue:0x176cba,blue2:0x69a8d9,sage:0x84b6aa,sea:0x9fc7d7,grass:0xdde5dc,wood:0xaa805a,yellow:0xd0a44f};
const M={white:new THREE.MeshStandardMaterial({color:C.white,roughness:.76,metalness:.04}),road:new THREE.MeshStandardMaterial({color:C.road,roughness:.9}),graphite:new THREE.MeshStandardMaterial({color:C.graphite,roughness:.52,metalness:.42}),deep:new THREE.MeshStandardMaterial({color:C.deep,roughness:.58,metalness:.38}),steel:new THREE.MeshStandardMaterial({color:C.steel,roughness:.42,metalness:.72}),alu:new THREE.MeshStandardMaterial({color:C.alu,roughness:.29,metalness:.9}),alu2:new THREE.MeshStandardMaterial({color:C.alu2,roughness:.31,metalness:.75}),blue:new THREE.MeshStandardMaterial({color:C.blue,roughness:.34,metalness:.4}),sage:new THREE.MeshStandardMaterial({color:C.sage,roughness:.82}),grass:new THREE.MeshStandardMaterial({color:C.grass,roughness:1}),wood:new THREE.MeshStandardMaterial({color:C.wood,roughness:.75}),yellow:new THREE.MeshStandardMaterial({color:C.yellow,roughness:.5,metalness:.18}),glass:new THREE.MeshPhysicalMaterial({color:0xb9d8e5,roughness:.08,transmission:.32,transparent:true,opacity:.58})};
scene.add(new THREE.HemisphereLight(0xffffff,0xb8b3a8,2.8));const sun=new THREE.DirectionalLight(0xffffff,4.0);sun.position.set(45,55,28);sun.castShadow=!mobile;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-120;sun.shadow.camera.right=120;sun.shadow.camera.top=90;sun.shadow.camera.bottom=-90;scene.add(sun);const fill=new THREE.DirectionalLight(0xc9e4ff,1.15);fill.position.set(-40,26,-30);scene.add(fill);
function mesh(g,geo,mat,pos=[0,0,0],rot=[0,0,0],cast=true){const m=new THREE.Mesh(geo,mat);m.position.set(...pos);m.rotation.set(...rot);m.castShadow=cast&&!mobile;m.receiveShadow=!mobile;g.add(m);return m}function box(g,s,p,mat=M.alu,r=[0,0,0]){return mesh(g,new THREE.BoxGeometry(...s),mat,p,r)}function cyl(g,r,d,p,mat=M.alu,rot=[0,0,0],seg=24){return mesh(g,new THREE.CylinderGeometry(r,r,d,seg),mat,p,rot)}
function canvasMat(text,bg='#176cba',fg='#ffffff',sub=''){const c=document.createElement('canvas');c.width=1024;c.height=256;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,c.width,c.height);x.fillStyle=fg;x.font='900 112px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,512,112);if(sub){x.font='600 30px Arial';x.globalAlpha=.88;x.fillText(sub,512,196)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return new THREE.MeshStandardMaterial({map:t,roughness:.42,metalness:.15})}
const allucoMat=canvasMat('ALLUCO','#176cba','#ffffff','ALUMINIUM SYSTEMS'); const allucoWhite=canvasMat('ALLUCO','#f7f7f4','#176cba','ALUMINIUM SYSTEMS');
const base=mesh(world,new THREE.PlaneGeometry(230,130),M.grass,[60,-2.2,0],[-Math.PI/2,0,0],false);box(world,[52,.12,42],[-50,-2.12,-21],M.white);box(world,[30,.12,28],[85,-2.12,35],M.white);box(world,[42,.12,30],[45,-2.12,-34],M.white);
function roadSegments(points,width=3.5){for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),ang=-Math.atan2(dz,dx);box(world,[len,.10,width],[(a[0]+b[0])/2,-2.08,(a[1]+b[1])/2],M.road,[0,ang,0]);box(world,[len,.012,.045],[(a[0]+b[0])/2,-2.015,(a[1]+b[1])/2],M.steel,[0,ang,0]).material.opacity=.35}}
const roadPts=[[-62,21],[-49,16],[-35,17],[-21,10],[-8,8],[4,13],[17,10],[30,3],[44,0],[58,4],[69,14],[82,16],[96,9],[110,2],[124,0]];roadSegments(roadPts,4.0);roadSegments([[-8,8],[-4,-6],[8,-18],[24,-26],[42,-30],[55,-28]],3.5);roadSegments([[58,4],[55,18],[66,29],[83,35]],3.4);
function tree(x,z,s=1){const g=new THREE.Group();g.position.set(x,-1.7,z);world.add(g);cyl(g,.12,1.3,[0,.2,0],M.wood);const crown=mesh(g,new THREE.IcosahedronGeometry(.8*s,1),M.sage,[0,1.35,0]);crown.scale.y=1.25}
for(let i=0;i<58;i++){const x=-68+Math.random()*190,z=-48+Math.random()*96;if(Math.abs(z)<7&&x>-50&&x<120)continue;tree(x,z,.65+Math.random()*.45)}
function building(x,z,w,d,h,accent=false){const g=new THREE.Group();g.position.set(x,-2.0,z);world.add(g);box(g,[w,h,d],[0,h/2,0],M.white);box(g,[w+.15,.16,d+.15],[0,h+.08,0],accent?M.blue:M.graphite);for(let i=-w*.35;i<=w*.35;i+=2.2)box(g,[.9,.5,.05],[i,h*.62,d/2+.03],M.glass);return g}
building(-37,-24,18,10,7,true);building(-55,2,12,9,5,false);building(20,29,14,9,6,false);building(105,-22,12,9,7,true);
// Airport terminal and aircraft zone
const airport=new THREE.Group();airport.position.set(-38,0,-28);world.add(airport);box(airport,[28,.12,20],[0,-2.05,0],M.white);box(airport,[18,4,5],[1,0,4],M.white);box(airport,[18,.18,5.1],[1,2.1,4],M.graphite);box(airport,[17,.9,.05],[1,.55,6.55],M.glass);for(let x=-9;x<=9;x+=6)box(airport,[.22,4,.22],[x,0,-3],M.steel);
function aircraft(scale=.6){const g=new THREE.Group();g.scale.setScalar(scale);cyl(g,.55,7.2,[0,0,0],M.alu2,[0,0,Math.PI/2],28);const n=mesh(g,new THREE.ConeGeometry(.57,1.3,28),M.alu2,[4.2,0,0],[0,0,-Math.PI/2]);box(g,[3.1,.12,9.2],[.1,0,0],M.alu2);box(g,[1.25,1.5,.12],[-3.1,.7,0],M.blue,[0,0,-.1]);return g}
const planeA=aircraft(.72);planeA.position.set(-41,-.7,-34);world.add(planeA);const planeB=aircraft(.56);planeB.position.set(-29,-.9,-31);planeB.rotation.y=.12;world.add(planeB);
// Truck factory with real ALLUCO branded trailers
function wheel(g,p,r=.38){return cyl(g,r,.22,p,M.deep,[0,0,Math.PI/2],20)}
function makeTruck(){const g=new THREE.Group();box(g,[2.15,1.85,1.85],[-2.9,.72,0],M.white);box(g,[1.35,.58,1.56],[-2.9,1.1,0],M.glass);box(g,[.95,.34,1.9],[-1.82,.13,0],M.graphite);box(g,[5.6,2.15,1.92],[1.5,.86,0],M.white);const side1=mesh(g,new THREE.PlaneGeometry(4.95,1.25),allucoMat,[1.52,1.05,.97],[0,0,0],false);const side2=mesh(g,new THREE.PlaneGeometry(4.95,1.25),allucoMat,[1.52,1.05,-.97],[0,Math.PI,0],false);box(g,[5.7,.11,1.98],[1.5,1.97,0],M.alu);[-3.0,-1.7,2.0,3.2].forEach(x=>[.98,-.98].forEach(z=>wheel(g,[x,-.2,z],x>1?.34:.4)));return g}
const roadCurve=new THREE.CatmullRomCurve3(roadPts.map(p=>new THREE.Vector3(p[0],-1.45,p[1])),false,'catmullrom',.18);const trucks=[];for(let i=0;i<7;i++){const t=makeTruck();t.scale.setScalar(.72);world.add(t);trucks.push({g:t,offset:i/7,speed:.010+(i%3)*.0015})}
// Port zone
const port=new THREE.Group();port.position.set(47,0,-31);world.add(port);const sea=mesh(world,new THREE.PlaneGeometry(48,30),new THREE.MeshStandardMaterial({color:C.sea,roughness:.26,metalness:.06,transparent:true,opacity:.58}),[50,-2.08,-45],[-Math.PI/2,0,0],false);box(port,[36,.22,14],[0,-2.0,3],M.white);
function container(g,p,mat=M.graphite,s=1){const q=new THREE.Group();q.position.set(...p);q.scale.setScalar(s);g.add(q);box(q,[3.0,1.4,1.35],[0,0,0],mat);for(let x=-1.2;x<=1.2;x+=.48)box(q,[.035,1.18,1.37],[x,0,0],M.steel);return q}
for(let x=-14;x<=8;x+=3.4)for(let z=-2;z<=7;z+=3)if((x+z)%2<1.2){container(port,[x,-.95,z],Math.random()>.72?M.blue:M.graphite,.75);if(Math.random()>.45)container(port,[x,.12,z],Math.random()>.75?M.blue:M.steel,.75)}
function gantry(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(s);port.add(g);[-4,4].forEach(px=>box(g,[.32,9,.32],[px,2.55,0],M.graphite));box(g,[8.6,.35,.35],[0,7.0,0],M.graphite);box(g,[11,.22,.22],[1.1,6.35,0],M.steel);return g}const craneA=gantry(11,1,1),craneB=gantry(2,1,.86);
const ship=new THREE.Group();ship.position.set(55,-.45,-44);world.add(ship);const hullShape=new THREE.Shape();hullShape.moveTo(-10,-.85);hullShape.lineTo(7.8,-.85);hullShape.lineTo(10,-.1);hullShape.lineTo(7.8,1.2);hullShape.lineTo(-8.5,1.2);hullShape.lineTo(-10,.2);hullShape.closePath();const hullGeo=new THREE.ExtrudeGeometry(hullShape,{depth:4.6,bevelEnabled:true,bevelSize:.12,bevelThickness:.12,bevelSegments:2});hullGeo.translate(0,0,-2.3);mesh(ship,hullGeo,M.deep);box(ship,[14,.3,4.7],[-.6,1.35,0],M.steel);box(ship,[2.8,3.7,3.3],[-6.7,3.05,0],M.white);box(ship,[2.15,.9,2.8],[-6.7,4.18,0],M.glass);let ci=0;[-3.7,-.3,3.1].forEach(x=>[-1.25,0,1.25].forEach(z=>{container(ship,[x,2.15,z],ci++%5===0?M.blue:M.graphite,.64);if(Math.abs(z)<.2||x<1)container(ship,[x,3.15,z],ci++%6===0?M.blue:M.steel,.64)}));
// Warehouse with ALLUCO signage, open side racks
const wh=new THREE.Group();wh.position.set(83,0,34);world.add(wh);box(wh,[30,.22,22],[0,-2.02,0],M.white);for(let x=-14;x<=14;x+=7){box(wh,[.2,8,.2],[x,1.8,-9.5],M.steel);box(wh,[.2,8,.2],[x,1.8,9.5],M.steel)}box(wh,[30,.28,22],[0,5.85,0],new THREE.MeshStandardMaterial({color:0xe6e8e7,transparent:true,opacity:.78,roughness:.75}));box(wh,[30,3.2,.3],[0,3.85,-9.6],M.white);const sign=mesh(wh,new THREE.PlaneGeometry(10,2.05),allucoMat,[0,4.25,-9.78],[0,Math.PI,0],false);
for(const side of[-1,1])for(let i=0;i<5;i++){const x=-11+i*5;for(let h=0;h<4;h++){box(wh,[4.2,.12,1.55],[x+1.8,-1.15+h*1.48,side*5.5],M.steel);if(h<3){box(wh,[1.25,.42,1.05],[x+1.0,-.87+h*1.48,side*5.5],M.alu2);box(wh,[1.25,.42,1.05],[x+2.7,-.87+h*1.48,side*5.5],i%2?M.graphite:M.blue)}}}
const forklift=new THREE.Group();forklift.position.set(-5,-.9,0);wh.add(forklift);box(forklift,[2.0,1.05,1.55],[0,0,0],M.graphite);box(forklift,[1.0,.9,1.4],[-.42,.76,0],M.glass);box(forklift,[.12,3.0,.12],[.95,.82,.52],M.steel);box(forklift,[.12,3.0,.12],[.95,.82,-.52],M.steel);box(forklift,[2.05,.08,.08],[1.9,-.42,.46],M.steel);box(forklift,[2.05,.08,.08],[1.9,-.42,-.46],M.steel);[[-.6,.8],[-.6,-.8],[.65,.8],[.65,-.8]].forEach((p,i)=>wheel(forklift,[p[0],-.65,p[1]],i<2?.43:.33));box(forklift,[.48,.22,1.55],[-.78,.25,0],M.blue);const pallet=new THREE.Group();pallet.position.set(2.65,-.15,0);forklift.add(pallet);box(pallet,[2.45,.12,1.36],[0,0,0],M.wood);for(let i=0;i<10;i++)box(pallet,[2.3,.08,.10],[0,.16+i*.10,-.48+(i%3)*.48],M.alu2);
// Aluminium display near end of route
const alu=new THREE.Group();alu.position.set(122,0,0);world.add(alu);for(let i=0;i<16;i++)box(alu,[11,.2,.2],[-1,-1.25+(i%8)*.34,-1.4+Math.floor(i/8)*2.8],M.alu2);const prof=new THREE.Group();prof.position.set(2.2,2.4,0);alu.add(prof);const sh=new THREE.Shape();sh.moveTo(-2.1,-2.1);sh.lineTo(2.1,-2.1);sh.lineTo(2.1,2.1);sh.lineTo(-2.1,2.1);sh.closePath();const hole=new THREE.Path();hole.moveTo(-1.48,-1.48);hole.lineTo(-1.48,1.48);hole.lineTo(1.48,1.48);hole.lineTo(1.48,-1.48);hole.closePath();sh.holes.push(hole);const pg=new THREE.ExtrudeGeometry(sh,{depth:5.4,bevelEnabled:true,bevelSize:.055,bevelThickness:.055,bevelSegments:2});pg.translate(0,0,-2.7);mesh(prof,pg,M.alu2);box(prof,[.24,3.6,5.55],[0,0,0],M.alu);box(prof,[3.6,.24,5.55],[0,0,0],M.alu);
// Map marker rings
function marker(x,z){const g=new THREE.Group();g.position.set(x,-1.75,z);world.add(g);const r=mesh(g,new THREE.RingGeometry(.35,.5,32),new THREE.MeshBasicMaterial({color:C.blue,side:THREE.DoubleSide,transparent:true,opacity:.75}),[0,0,0],[-Math.PI/2,0,0],false);return g}[-38,-5,47,83,122].forEach((x,i)=>marker(x,[ -28,8,-31,34,0][i]));
const cameraStops=[{pos:[12,65,86],target:[24,0,0]},{pos:[-31,28,32],target:[-36,0,-24]},{pos:[18,23,34],target:[13,-1,8]},{pos:[66,24,20],target:[49,0,-31]},{pos:[103,25,55],target:[83,0,34]},{pos:[143,18,28],target:[122,1,0]}];let wantedPos=new THREE.Vector3(...cameraStops[0].pos),wantedTarget=new THREE.Vector3(...cameraStops[0].target);camera.position.copy(wantedPos);camera.lookAt(wantedTarget);const A=new THREE.Vector3(),B=new THREE.Vector3();let current=0;
function scrollState(){const y=scrollY+innerHeight*.48;let idx=0,local=0;for(let i=0;i<sections.length;i++){const a=sections[i].offsetTop,b=i<sections.length-1?sections[i+1].offsetTop:document.documentElement.scrollHeight;if(y>=a&&y<b){idx=i;local=THREE.MathUtils.clamp((y-a)/Math.max(1,b-a),0,1);break}}return{idx,local}}
function update(){const s=scrollState();current=s.idx;stageBtns.forEach((b,i)=>b.classList.toggle('is-active',i===s.idx));labels.forEach(l=>l.classList.toggle('on',Number(l.dataset.label)===s.idx));const a=cameraStops[s.idx]||cameraStops.at(-1),b=cameraStops[Math.min(s.idx+1,cameraStops.length-1)],t=reduced?0:s.local*s.local*(3-2*s.local);wantedPos.copy(A.set(...a.pos).lerp(B.set(...b.pos),t));wantedTarget.copy(A.set(...a.target).lerp(B.set(...b.target),t));camera.position.lerp(wantedPos,reduced?1:.055);camera.lookAt(wantedTarget);forklift.position.x=-5+(s.idx===4?s.local:0)*8;prof.rotation.y=(s.idx===5?s.local:0)*.65}
const clock=new THREE.Clock();function animate(){const t=clock.getElapsedTime();update();if(!reduced){trucks.forEach((o,i)=>{const u=(t*o.speed+o.offset)%1,p=roadCurve.getPointAt(u),tan=roadCurve.getTangentAt(u);o.g.position.copy(p);o.g.position.y=-1.38;o.g.rotation.y=-Math.atan2(tan.z,tan.x)});planeA.position.x=-41+Math.sin(t*.11)*1.3;ship.position.x=55+Math.sin(t*.18)*.35;ship.position.y=-.45+Math.sin(t*.55)*.035;forklift.position.z=Math.sin(t*.45)*.2;prof.rotation.z=Math.sin(t*.18)*.02}renderer.render(scene,camera);requestAnimationFrame(animate)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.15:1.55))});prog(78,'LINKING AIR, ROAD, PORT & WAREHOUSE...');requestAnimationFrame(()=>{animate();prog(100,'READY');setTimeout(()=>loader.classList.add('off'),420)});
})();
</script>
</body>
</html>"""
components.html(SITE_HTML, height=1000, scrolling=True)
